### PR TITLE
Re-organise docs examples

### PR DESCRIPTION
**Pull request by skonik**
### Description of Change
Documentation examples are now grouped into subsections per example topic.
result

### Assumptions
-

### Checklist for All Submissions
* [ ] I have added change info to [CHANGES.rst](https://github.com/aio-libs/aiobotocore/blob/master/CHANGES.rst)
* [ ] If this is resolving an issue (needed so future developers can determine if change is still necessary and under what conditions) (can be provided via link to issue with these details):
  * [ ] Detailed description of issue
  * [ ] Alternative methods considered (if any)
  * [ ] How issue is being resolved
  * [ ] How issue can be reproduced 
* [ ] If this is providing a new feature  (can be provided via link to issue with these details):
  * [ ] Detailed description of new feature
  * [ ] Why needed
  * [ ] Alternatives methods considered (if any)

### Checklist when updating botocore and/or aiohttp versions

* [ ] I have read and followed [CONTRIBUTING.rst](https://github.com/aio-libs/aiobotocore/blob/master/CONTRIBUTING.rst#how-to-upgrade-botocore)
* [ ] I have updated test_patches.py where/if appropriate (also check if no changes necessary)
* [ ] I have ensured that the awscli/boto3 versions match the updated botocore version

### CODE REVIEW

**Comment by terrycain** [comment]
Let me know when your finished and i'll look through it

**Comment by thehesiod** [comment]
@terrycain is this ok to merge?

**Comment by terrycain** [comment]
Yep looks fine, just a bit of re-organisation it seems

**Comment by skonik** [comment]
Sorry, completely forgot about this.
Yes, this is just a simple re-organisation

**Comment by skonik** [comment]
Let's me fix some typos. In general currently we have this

https://user-images.githubusercontent.com/50069473/146407902-e3b2ddf7-c4b5-4c18-a9f3-b3eb964a8b85.mov

**Comment by thehesiod** [comment]
thanks!

**Pull request merged**
