### PR TITLE
bump up version

### PR DESCRIPTION
**Pull request by thehesiod**
changes to AioConfig were non-backwards compatible

### CODE REVIEW

**Comment by jettify** [comment]
Could you please squash commits? Also what do you think about releasing new version to pypi?

**Comment by thehesiod** [comment]
yes please! would you like to do that or want me try to do it for the first time? I just realized that the current release uses unlimited TCP connections by default which can be bad.  I'm trying to get to the bottom of an aiohttp resource leak I'm seeing

**Comment by jettify** [comment]
Please do it!

**Comment by jettify** [comment]
https://github.com/aio-libs/aiobotocore/releases and then `draft new release`

**Pull request merged**
