### PR TITLE
Support up-to-date `botocore` and `urllib3 2.0`

### LINKED ISSUE #1028: Be more permissive on boto3 version
Currently the boto3 version is
`'boto3': ['boto3>=1.26.161,<1.26.162']`
This causes lots of conflicts with other packages (in our case sagemaker)
Can the versions be something like
`'boto3': ['boto3>=1.26.161,<1.27.0']`?

### LINKED ISSUE #1043: Bump botocore to latest version
**Describe the bug**

aiobotocore dependency on botocore 1.31.17 causes dependency conflict with packages that depend on newer version of botocore. For example, because of this latest versions of s3fs and boto3 conflict.

**Additional context**

Opened PR #1042 bumping to address this

### PR DESCRIPTION
**Pull request by jakob-keller**
### Description of Change
This PR intends to improve general compatibility of `aiobotocore` within the Python ecosystem by relaxing the dependency specification of `botocore`, as well as `boto3` and `awscli`.

Thanks to https://github.com/boto/botocore/pull/3034, this PR also implicitly provides `support for urllib3 2.0 for Python 3.10+`. Installing `urllib3>=2.0.0` causes unit tests to fail due to an outdated development dependency. This PR bumps `docker` to address the issue.

### Assumptions
[Upstream diff](https://github.com/boto/botocore/compare/1.31.16..1.31.64) does not contain any changes that require adjustments to the `aiobotocore` codebase: Besides JSON data and docstring updates, there are only minor changes to `botocore` Python code and unit tests, none of which affect `aiobotocore`. This allows for the proposed widening of the `botocore` dependency specification.

### Checklist for All Submissions
* [x] I have added change info to [CHANGES.rst](https://github.com/aio-libs/aiobotocore/blob/master/CHANGES.rst)
* [x] If this is resolving an issue (needed so future developers can determine if change is still necessary and under what conditions) (can be provided via link to issue with these details): closes #1028, closes #1043, closes https://github.com/aws/sagemaker-distribution/issues/83, closes https://github.com/terrycain/aioboto3/issues/317
  * [x] Detailed description of issue
  * [ ] Alternative methods considered (if any)
  * [x] How issue is being resolved
  * [ ] How issue can be reproduced
* [ ] If this is providing a new feature  (can be provided via link to issue with these details):
  * [ ] Detailed description of new feature
  * [ ] Why needed
  * [ ] Alternatives methods considered (if any)

### Checklist when updating botocore and/or aiohttp versions

* [x] I have read and followed [CONTRIBUTING.rst](https://github.com/aio-libs/aiobotocore/blob/master/CONTRIBUTING.rst#how-to-upgrade-botocore)
* [x] I have updated test_patches.py where/if appropriate (also check if no changes necessary)
* [x] I have ensured that the awscli/boto3 versions match the updated botocore version

### CODE REVIEW

**Comment by jakob-keller** [comment]
@thehesiod: Would you mind having a brief look at this PR? It should be trivial to review, IMHO. Thank you!

**Comment by JackKolb-ElationHealth** [comment]
Any chance we could bump even higher? I'm trying to get a service definition for AWS bedrock supported across both aiobotocore and aioboto3.  That requires a botocore bump to atleast [1.31.57](https://github.com/boto/botocore/blob/develop/CHANGELOG.rst#13157).

Is this wishful thinking?

**Comment by jakob-keller** [comment]
> I think this will help me with another issue. I'm trying to get a service definition for AWS bedrock supported across both aiobotocore and aioboto3. That requires a botocore bump to atleast [1.31.57](https://github.com/boto/botocore/blob/develop/CHANGELOG.rst#13157).

That should be possible once this PR is merged and a release is published.

**Comment by jakob-keller** [comment]
Until this PR is reviewed, I intend to monitor `botocore` releases and push updates to prevent the PR from becoming stale.

**Comment by just4brown** [comment]
Hi team, looks like we have a lot of folks blocked waiting for this change. Any maintainers available to review this? cc @thehesiod @terrycain @jettify 

Thanks!

**Comment by jchacks** [comment]
Pinning to a patch version of `botocore` is very restrictive. Can the upper bound on `'botocore>=1.31.16,<1.31.63',` be relaxed to `<1.32.0`?  This is the same as `boto3`'s upper bound on botocore found in https://github.com/boto/boto3/blob/develop/setup.py

**Comment by jakob-keller** [comment]
> Pinning to a patch version of `botocore` is very restrictive.

Agreed.

> Can the upper bound on `'botocore>=1.31.16,<1.31.63',` be relaxed to `<1.32.0`?

Unfortunately, this is not possible due to the [tight integration between botocore and aiobotocore](https://github.com/aio-libs/aiobotocore/blob/master/CONTRIBUTING.rst#background-and-implementation).

**Comment by paulmueller** [comment]
Note that there has been a dependency breakage with urllib3/requests/botocore for some time now which is resolved at least for users of Python>=3.10 in the latest releases of botocore (https://github.com/boto/botocore/issues/2926#issuecomment-1749856157).

Bumping the version of botocore in aiobotocore would resolve this for projects that have other dependencies that require `urllib3>2`.

**Comment by thehesiod** [comment]
looking! sorry for delay, have been super busy

**Review by thehesiod — APPROVED** [review]

**Comment by thehesiod** [comment]
my apologies for delay!  kids/work/personal stuff has been honestly overwhelming this last month.  Deploying shortly

**Comment by jakob-keller** [comment]
> my apologies for delay! kids/work/personal stuff has been honestly overwhelming this last month. Deploying shortly

We hear you! 😄

**Comment by thehesiod** [comment]
FYI merging 2.7.0 + 2.7.1 in https://github.com/aio-libs/aiobotocore/pull/1034 as 2.7.0 was never released

**Comment by jakob-keller** [comment]
> FYI merging 2.7.0 + 2.7.1 in #1034 as 2.7.0 was never released

Sorry, my bad!

**Comment by paulmueller** [comment]
Sorry for posting on a closed PR. Is there any reason why botocore was pinned to

- `botocore<1.31.65,>=1.31.16`

instead of

- `botocore<=1.31.65,>=1.31.16`


The problem I am having is that  `boto3 1.28.65 requires botocore<1.32.0,>=1.31.65`.

So I am stuck with `urllib3<2` and cannot use the latest versions of `aiobotocore` and [s3fs](https://github.com/fsspec/s3fs/issues/801).

**Comment by jakob-keller** [comment]
> Sorry for posting on a closed PR. Is there any reason why botocore was pinned to
> 
> * `botocore<1.31.65,>=1.31.16`
> 
> instead of
> 
> * `botocore<=1.31.65,>=1.31.16`

`botocore==1.31.65` was released after this PR was prepared and merged. Supporting `botocore==1.31.65` would be trivial, but requires a separate PR and release.

You should be able to gain the benefits of this PR, if you work with `boto3<=1.28.64`.

**Comment by paulmueller** [comment]
Yes thanks, you are correct. The install works, albeit with a quite old version of s3fs.

```
$ pip install boto3==1.28.64 aiobotocore s3fs "urllib3>=2.0"
$ pip freeze
aiobotocore==2.7.0
aiohttp==3.8.6
aioitertools==0.11.0
aiosignal==1.3.1
async-timeout==4.0.3
attrs==23.1.0
boto3==1.28.64
botocore==1.31.64
charset-normalizer==3.3.0
frozenlist==1.4.0
fsspec==2021.7.0
idna==3.4
jmespath==1.0.1
multidict==6.0.4
python-dateutil==2.8.2
s3fs==2021.7.0
s3transfer==0.7.0
six==1.16.0
urllib3==2.0.7
wrapt==1.15.0
yarl==1.9.2
```

**Comment by potiuk** [comment]
> Yes thanks, you are correct. The install works, albeit with a quite old version of s3fs (so I am waiting for s3fs to support aiobotocore 2.7.0).

Same here. Already merged in https://github.com/fsspec/s3fs/pull/809

**Comment by potiuk** [comment]
And.... THANKS. This one will solves a lof of our probllems  in Apache Airflow ! We had to figure out a very weird scheme there

**Pull request merged**
