### PR TITLE
Switch to PyPI trusted publishing (#1116)

### LINKED ISSUE #1116: Switch CI/CD to PyPI trusted publishing
Just got a warning from PyPI:
Screenshot_2024-05-16-16-17-11-73_e307a3f9df9f380ebaf106e1dc980bb6

To fix this, GHA should be configured similarly to aiomonitor.

### PR DESCRIPTION
**Pull request by jakob-keller**
### Description of Change
Switch to PyPI trusted publishing

### Assumptions
Trusted publisher is configured for this project.

### Checklist for All Submissions
* [ ] I have added change info to [CHANGES.rst](https://github.com/aio-libs/aiobotocore/blob/master/CHANGES.rst)
* [x] If this is resolving an issue (needed so future developers can determine if change is still necessary and under what conditions) (can be provided via link to issue with these details): closes #1116
  * [ ] Detailed description of issue
  * [ ] Alternative methods considered (if any)
  * [ ] How issue is being resolved
  * [ ] How issue can be reproduced
* [ ] If this is providing a new feature  (can be provided via link to issue with these details):
  * [ ] Detailed description of new feature
  * [ ] Why needed
  * [ ] Alternatives methods considered (if any)

### Checklist when updating botocore and/or aiohttp versions

* [ ] I have read and followed [CONTRIBUTING.rst](https://github.com/aio-libs/aiobotocore/blob/master/CONTRIBUTING.rst#how-to-upgrade-botocore)
* [ ] I have updated test_patches.py where/if appropriate (also check if no changes necessary)
* [ ] I have ensured that the awscli/boto3 versions match the updated botocore version

### CODE REVIEW

**Review by thehesiod — APPROVED** [review]

**Comment by jakob-keller** [comment]
@thehesiod: Do you want to give the new publishing action a spin? :-)

**Comment by webknjaz** [comment]
I'd check the trusted publishing config first. It's standardized around different naming in the org so your workflow will probably not match..

**Comment by webknjaz** [comment]
@jakob-keller The job name and the environment name have to match the following values: 


You'll need a follow-up PR to make it work.

**Comment by thehesiod** [comment]
> @thehesiod: Do you want to give the new publishing action a spin? :-)

based on @webknjaz 's reply sounds like we need a follow-up?

**Comment by jakob-keller** [comment]
Sure, will do in a few hours. Sorry for jumping the gun on this one and thanks @webknjaz for your guidance!

**Pull request merged**
