### PR TITLE
Bump boto* versions

### PR DESCRIPTION
**Pull request by Fokko**
### Description of Change

Bumped the boto versions because I would love to use the bearer authentication: https://github.com/boto/botocore/commit/e5e848a3c9c2c94e36c62d930b0dc42b93c29d43

### Assumptions

Everything is still compatible

### Checklist for All Submissions
* [x] I have added change info to [CHANGES.rst](https://github.com/aio-libs/aiobotocore/blob/master/CHANGES.rst)
* [ ] If this is resolving an issue (needed so future developers can determine if change is still necessary and under what conditions) (can be provided via link to issue with these details):
  * [ ] Detailed description of issue
  * [ ] Alternative methods considered (if any)
  * [ ] How issue is being resolved
  * [ ] How issue can be reproduced
* [ ] If this is providing a new feature  (can be provided via link to issue with these details):
  * [ ] Detailed description of new feature
  * [ ] Why needed
  * [ ] Alternatives methods considered (if any)

### Checklist when updating botocore and/or aiohttp versions

* [x] I have read and followed [CONTRIBUTING.rst](https://github.com/aio-libs/aiobotocore/blob/master/CONTRIBUTING.rst#how-to-upgrade-botocore)
* [x] I have updated test_patches.py where/if appropriate (also check if no changes necessary)
* [x] I have ensured that the awscli/boto3 versions match the updated botocore version

### CODE REVIEW

**Comment by thehesiod** [comment]
yes going to try to get some PRs merged today

**Comment by Fokko** [comment]
@thehesiod do you have some spare cycles to look into this? It looks like some response has changed, but I'm struggling to find where to fix this in the code.

**Comment by thehesiod** [comment]
my apologies for delays, always crazy with kids, both our kids had bdays recently along with big work push

**Comment by Fokko** [comment]
@thehesiod No worries, I know all about it :) Congratulations on the birthdays!

**Comment by thehesiod** [comment]
working on it now! :)

**Comment by thehesiod** [comment]
btw tip for next time, you need to do a directory diff across the two versions and apply any changes to methods we've overridden.  I'm having to do it myself again

**Comment by thehesiod** [comment]
here some work: https://github.com/aio-libs/aiobotocore/pull/974 unfortunately it seems like they've added a new async path for refreshing tokens that we'll need to override :(. If you'd like to help mind researching that part?

**Comment by Fokko** [comment]
I don't have sufficient knowledge of boto to fix this.

**Comment by thehesiod** [comment]
ok will continue asap

**Comment by lorenzwalthert** [comment]
Are there any plans for the near future to bump boto versions? Since version 2.123.0 (3 weeks ago), new sagemaker SDK releases are no longer compatible with this library because the [introducrtion of sagemaker epxeriment functionality](https://github.com/aws/sagemaker-python-sdk/pull/3536) required [`boto3 >=1.26.28`](https://github.com/aws/sagemaker-python-sdk/blob/v2.123.0/setup.py#L51).

**Pull request closed without merging**
