### PR TITLE
correct awscli version range Fixes #460

### LINKED ISSUE #460: aiobotocore[awscli] at wrong version
https://github.com/aws/aws-cli/blob/1.11.146/setup.py#L26

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@jettify can you merge this one as ASAP as possible please, my build breaks without a valid awscli, botocore and aiobotocore installed.

**Comment by jettify** [comment]
makes sense

**Comment by graingert** [comment]
@jettify can I get a release please?

**Comment by jettify** [comment]
done https://pypi.python.org/pypi/aiobotocore/0.5.2

**Pull request merged**
