### PR TITLE
add support for latest aiohttp/botocore

### PR DESCRIPTION
**Pull request by thehesiod**

### CODE REVIEW

**Comment by thehesiod** [comment]
@jettify can we update the unittests to run against multiple versions of botocore?  Perhaps earliest and latest releases supported.  that would expand the test coverage.

**Comment by jettify** [comment]
Can do that, but should we just set minimal version `1.5.71` and max `1.5.78`? I mean for `<=1.5.70` users may use older `aiobotocore` versions... Feature vise `aiobotocore` is same, just different supported `botocore` versions.

**Comment by thehesiod** [comment]
ah, so we don't need the hack?  ya I can do that

**Comment by thehesiod** [comment]
btw I'm working with asvetlov on aiohttp work-around, next release should have the fix for 3.4

**Comment by jettify** [comment]
I am fine with either your solutions, my point having less code is better and easier to maintain :)

**Comment by thehesiod** [comment]
going to delay this till we get 2.2.3 tomorrow so we can remove the hack

**Pull request merged**
