### PR TITLE
Support customizing the aiohttp connector resolver class

### LINKED ISSUE #892: Allow customizing the aiohttp resolver class
ref: https://github.com/dask/s3fs/issues/543

In https://github.com/aio-libs/aiobotocore/blob/master/aiobotocore/config.py#L31 we have a small allowlist of keyword arguments we validate against. Unfortunately it's not possible to pass a custom `resolver` into `aiohttp`, which should allow requests to be made during interpreter shutdown because a new thread won't be spawned to do a DNS lookup.

Is there any reason we don't allow customizing the resolver? Being able to do:

```python
from aiohttp.resolver import AsyncResolver

AioConfig(connector_args={"resolver": AsyncResolver})
```

would be perfect.

### PR DESCRIPTION
**Pull request by orf**
### Description of Change

Closes #892. I did this in github editor, I'll fix up and add tests tomorrow.

### Assumptions
*Replace this text with any assumptions made (if any)*

### Checklist for All Submissions
* [x] I have added change info to [CHANGES.rst](https://github.com/aio-libs/aiobotocore/blob/master/CHANGES.rst)
* [x] If this is resolving an issue (needed so future developers can determine if change is still necessary and under what conditions) (can be provided via link to issue with these details):
  * [ ] Detailed description of issue
  * [ ] Alternative methods considered (if any)
  * [ ] How issue is being resolved
  * [ ] How issue can be reproduced 
* [x] If this is providing a new feature  (can be provided via link to issue with these details):
  * [ ] Detailed description of new feature
  * [ ] Why needed
  * [ ] Alternatives methods considered (if any)

### Checklist when updating botocore and/or aiohttp versions

* [x] I have read and followed [CONTRIBUTING.rst](https://github.com/aio-libs/aiobotocore/blob/master/CONTRIBUTING.rst#how-to-upgrade-botocore)
* [x] I have updated test_patches.py where/if appropriate (also check if no changes necessary)
* [x] I have ensured that the awscli/boto3 versions match the updated botocore version

### CODE REVIEW

**Review by thehesiod — APPROVED** [review]

**Comment by orf** [comment]
Added a test and added to the changelog

**Comment by thehesiod** [comment]
doh, forgot I needed to approve tests for first time contributors

**Comment by thehesiod** [comment]
@orf looks like you have a couple tests that failed

**Comment by thehesiod** [comment]
btw just published 2.x, you'll want to bump your changes

**Comment by orf** [comment]
Done!

**Comment by orf** [comment]
@thehesiod there was an error in the changelog entry, I'm not sure what's up with that. I've removed the changes to the changelog file.

**Comment by thehesiod** [comment]
There's a test that verifies the changelog version matches the actual in init.py. i can add later (hope i remember). If you'd like to open an issue about that i can take care of it otherwise i think you can make it a dev ver

**Comment by orf** [comment]
Let's just merge this and sort the changelog out later? I've got some upstream work that is blocked by this

**Comment by thehesiod** [comment]
Will do. Sorry for delay, working out some citizenship issues in an area
with very bad internet

**Comment by orf** [comment]
> Will do. Sorry for delay, working out some citizenship issues in an area with very bad internet
> […](#)

Absolutely no problem, you’re not beholden to me or any timeline. I hope all goes well.

**Pull request merged**
