### PR TITLE
Poetry packaging

### LINKED ISSUE #833: Use in AWS Lambda with minimal layer sizes
It would help if the test-CI matrix and the setup dependencies supported the current versions of AWS Lambda for boto3 and botocore.  It would be useful if one cell in a test-CI matrix pinned the boto3/botocore versions to the exact patch versions used in the current AWS Lambda runtime versions (and possibly ran in a container using the lambci runtime used by AWS Lambda for each python version in the runtimes available; excluding anything that does not support asyncio, of course).  At the time of writing, the setup.py does not allow a range of botocore or boto3 versions that are compatible with the current AWS Lambda versions; the current AWS Lambda runtime versions are listed in [1] as follows.

[1] https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

```
Python runtimes
--

Python 3.8 | python3.8 | boto3-1.14.40 botocore-1.17.40 | Amazon Linux 2
Python 3.7 | python3.7 | boto3-1.14.40 botocore-1.17.40 | Amazon Linux
Python 3.6 | python3.6 | boto3-1.14.40 botocore-1.17.40 | Amazon Linux
Python 2.7 | python2.7 | boto3-1.14.40 botocore-1.17.40 | Amazon Linux
```

The `setup.py` contains the following at the time of writing:

```python
install_requires = [
    # pegged to also match items in `extras_require`
    'botocore>=1.17.44,<1.17.45',
    'aiohttp>=3.3.1',
    'wrapt>=1.10.10',
    'aioitertools>=0.5.1',
]
extras_require = {
    'awscli': ['awscli==1.18.121'],
    'boto3': ['boto3==1.14.44'],
}
```

It could help if `setup.py` could keep track of AWS Lambda runtime versions and allow a range of versions that are compatible, e.g. maybe (?)

```python
    'botocore>=1.17.40,<1.17.45',

    'boto3': ['boto3>=1.14.40,<1.14.45'],
```

Of course, doing so would entail that a test-CI matrix uses the actual AWS Lambda pinned versions to check that everything works OK with those releases.  Then it should be possible to easily and confidently use aiobotocore in AWS Lambda layers and functions.

It might be interesting to try lambCI
- https://github.com/lambci/lambci
- https://stackshare.io/stackups/lambci-vs-travis-ci
- but it seems to require an AWS account for a CloudFormation deployment (it's not a service)

### Motivation for Specific AWS Lambda Compatibility

Of course, it is always possible to bundle a different boto3/botocore into an AWS Lambda layer or function and carry on regardless of whatever the AWS Lambda runtime provides out of the box.  However, sometimes a project may have so many dependencies or multiple layers that it exceeds the AWS package size limits [2].  In some serverless applications, the size of a lambda layer can approach the limits of layer sizes.  In these cases, it helps to delete boto3 and all of its dependencies from a layer zip archive, because the lambda runtime container already provides them out-of-the-box.  Doing so can save a big chunk of space in an AWS Lambda layer.  The following example is the dep-tree for the current AWS Lambda boto3 version:

```
$ pipdeptree -p boto3
boto3==1.14.40
  - botocore [required: >=1.17.40,<1.18.0, installed: 1.17.40]
    - docutils [required: >=0.10,<0.16, installed: 0.15.2]
    - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.5]
    - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.1]
      - six [required: >=1.5, installed: 1.14.0]
    - urllib3 [required: >=1.20,<1.26, installed: 1.25.9]
  - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.5]
  - s3transfer [required: >=0.3.0,<0.4.0, installed: 0.3.3]
    - botocore [required: >=1.12.36,<2.0a.0, installed: 1.17.40]
      - docutils [required: >=0.10,<0.16, installed: 0.15.2]
      - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.5]
      - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.1]
        - six [required: >=1.5, installed: 1.14.0]
      - urllib3 [required: >=1.20,<1.26, installed: 1.25.9]
```

[2] https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html

### PR DESCRIPTION
**Pull request by dazza-codes**
Fix #833 although it does not use a lambci docker container in the travis-CI matrix.

This PR is a response to difficulty on a couple of other PRs when I can't grapple with pipenv for my dev-env.  There might be bits-n-pieces of this PR that are welcome and other bits that are not.  I'm open to discussion, testing and compromises.  I'm not having much success with pipenv.  Even if this PR is not adopted/merged, I will find it useful to work with this branch and rebase on master and manage a parallel set of poetry-deps as needed.

This is an attempt to use poetry packaging for the project and it might be a contentious PR/issue, depending on dev-team preferences for dev-env setups.  In using poetry for the past year or so, this PR represents some patterns that are working consistently for me.  Hopefully the added files are mostly self-explanatory, please ask any questions to clarify things and take it for a spin on your local to see how it works out.

## TODO

- update CI/CD to use poetry
- contributions require using python 3.8 now (?)
- tests might assume there is a default profile available to get credentials (?), lots of failures without it

### CODE REVIEW

**Comment by thehesiod** [comment]
hmm perhaps aioboto should switch to pyproject.toml as well. Sorry really behind in the forward looking PRs, will try to look soon just been super busy since move, or maybe another aioboto admin can chime in =)

**Comment by dazza-codes** [comment]
The packaging and CI is running now, but I don't know how to fix the unit-test crash (and I can replicate it on my laptop dev-env, it's not just travis):

```
scheduling tests via LoadScheduling
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/travis/build/aio-libs/aiobotocore/venv/lib/python3.6/site-packages/_pytest/main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/travis/build/aio-libs/aiobotocore/venv/lib/python3.6/site-packages/_pytest/main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/travis/build/aio-libs/aiobotocore/venv/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/travis/build/aio-libs/aiobotocore/venv/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/build/aio-libs/aiobotocore/venv/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/travis/build/aio-libs/aiobotocore/venv/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/home/travis/build/aio-libs/aiobotocore/venv/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/travis/build/aio-libs/aiobotocore/venv/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/build/aio-libs/aiobotocore/venv/lib/python3.6/site-packages/xdist/dsession.py", line 112, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/home/travis/build/aio-libs/aiobotocore/venv/lib/python3.6/site-packages/xdist/dsession.py", line 135, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/home/travis/build/aio-libs/aiobotocore/venv/lib/python3.6/site-packages/xdist/dsession.py", line 174, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('tests/test_basic_s3.py::test_fail_proxy_request', <WorkerController gw1>)
INTERNALERROR> assert not 'tests/test_basic_s3.py::test_fail_proxy_request'
```

**Comment by thehesiod** [comment]
@dazza-codes given that botocore has swapped to **https://github.com/boto/botocore/blob/develop/pyproject.toml** seems like this now makes even more sense, thoughts?

**Comment by lafrenierejm** [comment]
@dazza-codes I rebased on this PR to fix unit tests and linting in my fork: [lafrenierejm/aiobotocore/tree/poetry-packaging](https://github.com/lafrenierejm/aiobotocore/tree/poetry-packaging). Would you consider resetting this PR to my updated branch? Or would you prefer that I open a separate PR for review?

**Comment by thehesiod** [comment]
could you work with https://github.com/aio-libs/aiobotocore/pull/975 so we get a PR that includes both aspects?  thanks!

**Comment by jakob-keller** [comment]
@thehesiod: Would you agree that this PR is stale and may be closed at this point?

**Comment by thehesiod** [comment]
> @thehesiod: Would you agree that this PR is stale and may be closed at this point?

yep agreed, a ton has changed.  We should have an issue to discuss this about where we want to head, so many tools

**Comment by jakob-keller** [comment]
> yep agreed, a ton has changed. We should have an issue to discuss this about where we want to head, so many tools

Closing it for now. Anyone interested in modernizing dependency management and packaging tooling, open an issue or start a discussion.

**Pull request closed without merging**
