### PR TITLE
Improve compliance with Sphinx syntax in documentation

### LINKED ISSUE #1162: Improve use of Sphinx syntax
FWIW, there's a dedicated Sphinx role for files:
```suggestion
1. Download sources of the release of botocore you're trying to upgrade to, and the version of botocore that aiobotocore is currently locked to (see :file:`pyproject.toml`) and do a folder based file comparison of the botocore folders (tools like DiffMerge are nice).
```

_Originally posted by @webknjaz in https://github.com/aio-libs/aiobotocore/pull/1160#discussion_r1724142565_

### PR DESCRIPTION
**Pull request by jakob-keller**
### Description of Change
Closes #1162

### Assumptions
None

### Checklist for All Submissions
* [ ] I have added change info to [CHANGES.rst](https://github.com/aio-libs/aiobotocore/blob/master/CHANGES.rst)
* [ ] If this is resolving an issue (needed so future developers can determine if change is still necessary and under what conditions) (can be provided via link to issue with these details):
  * [ ] Detailed description of issue
  * [ ] Alternative methods considered (if any)
  * [ ] How issue is being resolved
  * [ ] How issue can be reproduced
* [ ] If this is providing a new feature  (can be provided via link to issue with these details):
  * [ ] Detailed description of new feature
  * [ ] Why needed
  * [ ] Alternatives methods considered (if any)

### Checklist when updating botocore and/or aiohttp versions

* [ ] I have read and followed [CONTRIBUTING.rst](https://github.com/aio-libs/aiobotocore/blob/master/CONTRIBUTING.rst#how-to-upgrade-botocore)
* [ ] I have updated test_patches.py where/if appropriate (also check if no changes necessary)
* [ ] I have ensured that the awscli/boto3 versions match the updated botocore version

### CODE REVIEW

**Comment by webknjaz** [comment]
I'd imagine those single backticks would just become double instead of italics. That was probably the original intent behind having the backticks in the first place..

**Comment by jakob-keller** [comment]
> I'd imagine those single backticks would just become double instead of italics. That was probably the original intent behind having the backticks in the first place..

Thanks, that makes sense. Pushed double backticks... Looks like `readthedocs.org`CI is broken.

**Comment by jakob-keller** [comment]
And we're back...

**Comment by webknjaz** [comment]
Remember to add `-n -W --keep-going` to the invocation in a follow-up.

**Pull request merged**
