### PR TITLE
resolve read_timeout

### PR DESCRIPTION
**Pull request by thehesiod**
- fixes https://github.com/aio-libs/aiobotocore/issues/245
- cleanup by moving more code to use wrapt
- implement set_socket_timeout

### CODE REVIEW

**Comment by thehesiod** [comment]
hey Jettify, let me know what you think.  All this because aiohttp dev didn't want to fix a core issue in their impl :(

**Comment by jettify** [comment]
I think aiohttp will do right thing eventually, we just need to make sure we can remove it easily and be very careful for each aiohttp release.

By the way next aiohttp will have new multi dict that preserves original headers

**Comment by thehesiod** [comment]
We shall see since I can't drive that anymore given his response.  Should I merge this PR or would you like me change something? Thanks!

**Comment by jettify** [comment]
change looks good, it uses a bit internal API but I do not see better way. We can merge, but lets do not close #245 at some point we need revert this PR once aiohttp ready

**Comment by thehesiod** [comment]
@jettify take a look at the last commit :)  Will make our lives easier

**Pull request merged**
