### PR TITLE
Update botocore version

### PR DESCRIPTION
**Pull request by terrycain**
Ok, not knowing exactly what needs to be done, I updated botocore to the latest version, added that to the requirements, made whatever classes that didn't match the hashes, match, then updated the hashes.

All the tests seem to work, so that's a start. @jettify Whats next?

### CODE REVIEW

**Comment by terrycain** [comment]
Hmm, its complaining about it not having coverage of a log line. Did a quick google and didn't turn up a quick test to trigger that.

**Comment by jettify** [comment]
I think change looks good, but PR should be updated.

**Comment by jettify** [comment]
Comparison between versions https://github.com/boto/botocore/compare/1.8.21...1.10.4

**Comment by terrycain** [comment]
Resolved conflicts :D

**Comment by terrycain** [comment]
:D tests pass now

**Comment by terrycain** [comment]
@jettify this PR ok?

**Comment by jettify** [comment]
PR is OK but looks like @thehesiod has similar changes + more enabled tests

**Comment by terrycain** [comment]
Ahh yeah that one looks better :D. Any idea when it'll be merged, later version of botocore would be rather helpful

**Comment by jettify** [comment]
PR https://github.com/aio-libs/aiobotocore/pull/576 merged

**Comment by terrycain** [comment]
Thanks :D

**Pull request closed without merging**
