### PR TITLE
Support up-to-date `botocore`

### PR DESCRIPTION
**Pull request by jakob-keller**
### Description of Change
This PR intends to improve general compatibility of `aiobotocore` within the Python ecosystem by relaxing the dependency specification of `botocore`, as well as `boto3` and `awscli`.

### Assumptions
* [Upstream diff](https://github.com/boto/botocore/compare/1.34.131..1.34.162) contains no relevant functional changes that require adjustments to the `aiobotocore` codebase.
* Upstream modernized its tooling, replacing `pyupgrade`, `black`, and `flake8` by `ruff`. As a result, there are numerous formatting related diffs, which have been integrated into this codebase.
* In order to keep tooling aligned with upstream, `aiobotocore` also migrates to `ruff` for linting and formatting. This results in a number of additional changes, primarily related to formatting.

### Checklist for All Submissions
* [x] I have added change info to [CHANGES.rst](https://github.com/aio-libs/aiobotocore/blob/master/CHANGES.rst)
* [ ] If this is resolving an issue (needed so future developers can determine if change is still necessary and under what conditions) (can be provided via link to issue with these details):
  * [ ] Detailed description of issue
  * [ ] Alternative methods considered (if any)
  * [ ] How issue is being resolved
  * [ ] How issue can be reproduced
* [ ] If this is providing a new feature  (can be provided via link to issue with these details):
  * [ ] Detailed description of new feature
  * [ ] Why needed
  * [ ] Alternatives methods considered (if any)

### Checklist when updating botocore and/or aiohttp versions

* [x] I have read and followed [CONTRIBUTING.rst](https://github.com/aio-libs/aiobotocore/blob/master/CONTRIBUTING.rst#how-to-upgrade-botocore)
* [x] I have updated test_patches.py where/if appropriate (also check if no changes necessary)
* [x] I have ensured that the awscli/boto3 versions match the updated botocore version

### CODE REVIEW

**Comment by jakob-keller** [comment]
@thehesiod: botocore just released 1.35.0 which contains a bunch of new logic. Before diving into that, I would love to merge this PR which provides compatibility for all recent 1.34.x releases.

Despite what codecov reports, test coverage is not actually any worse. The changes are purely due to new formatting provided by ruff. Yet, this is still blocking auto-merging for me.

Thanks for reviewing!

**Comment by jakob-keller** [comment]
@thehesiod: This would be the first PR to review ;-)

**Review by thehesiod — APPROVED** [review]

**Comment by jakob-keller** [comment]
@thehesiod: Thanks for reviewing and approving! You would need to perform the merge, since CodeCov isn't happy (enough). Also, this would be a candidate for a release, if you don't mind.

**Comment by jakob-keller** [comment]
Sorry, for all these PRs: I hope I'm not bothering you too much, @thehesiod!

**Comment by thehesiod** [comment]
> Sorry, for all these PRs: I hope I'm not bothering you too much, @thehesiod!

no bother at all! thank you for all the help!

**Pull request merged**
