### PR TITLE
Add support for Python 3.11

### PR DESCRIPTION
**Pull request by hugovk**
### Description of Change

Python 3.11 was [released on 2022-10-24](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk).

[image](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk)

Add 3.11 to CI and Trove classifiers. Also bump GitHub Actions and [drop the dot in py.test](https://twitter.com/pytestdotorg/status/753767547866972160).

### Checklist for All Submissions
* [x] I have added change info to [CHANGES.rst](https://github.com/aio-libs/aiobotocore/blob/master/CHANGES.rst)
* [ ] If this is resolving an issue (needed so future developers can determine if change is still necessary and under what conditions) (can be provided via link to issue with these details):
  * [ ] Detailed description of issue
  * [ ] Alternative methods considered (if any)
  * [ ] How issue is being resolved
  * [ ] How issue can be reproduced
* [ ] If this is providing a new feature  (can be provided via link to issue with these details):
  * [ ] Detailed description of new feature
  * [ ] Why needed
  * [ ] Alternatives methods considered (if any)

### Checklist when updating botocore and/or aiohttp versions

* [x] I have read and followed [CONTRIBUTING.rst](https://github.com/aio-libs/aiobotocore/blob/master/CONTRIBUTING.rst#how-to-upgrade-botocore)
* [x] I have updated test_patches.py where/if appropriate (also check if no changes necessary)
* [ ] I have ensured that the awscli/boto3 versions match the updated botocore version

### CODE REVIEW

**Review by Fokko — APPROVED** [review]
Would be great to support 3.11

**Comment by phillipuniverse** [comment]
Looks like we will need to also update botocore to at least 1.29.13 to remove new DeprecationWarning.

```
../../Library/Caches/pypoetry/virtualenvs/tabula-3sZz9FDu-py3.11/lib/python3.11/site-packages/aioboto3/__init__.py:5: in <module>
    from aioboto3.session import Session
../../Library/Caches/pypoetry/virtualenvs/tabula-3sZz9FDu-py3.11/lib/python3.11/site-packages/aioboto3/session.py:9: in <module>
    import aiobotocore.session
../../Library/Caches/pypoetry/virtualenvs/tabula-3sZz9FDu-py3.11/lib/python3.11/site-packages/aiobotocore/session.py:1: in <module>
    from botocore import UNSIGNED, translate
../../Library/Caches/pypoetry/virtualenvs/tabula-3sZz9FDu-py3.11/lib/python3.11/site-packages/botocore/translate.py:16: in <module>
    from botocore.utils import merge_dicts
../../Library/Caches/pypoetry/virtualenvs/tabula-3sZz9FDu-py3.11/lib/python3.11/site-packages/botocore/utils.py:15: in <module>
    import cgi
../../.pyenv/versions/3.11.1/lib/python3.11/cgi.py:57: in <module>
    warnings._deprecated(__name__, remove=(3,13))
../../.pyenv/versions/3.11.1/lib/python3.11/warnings.py:514: in _deprecated
    warn(msg, DeprecationWarning, stacklevel=3)
E   DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
```

See https://github.com/boto/botocore/commit/de07ce2c10bbd03b7ff75e283229a355baeeca63

**Comment by thehesiod** [comment]
@hugovk we've finally bumped, could you re-base and set to 2.5.1?

**Comment by hugovk** [comment]
Rebased!

**Comment by thehesiod** [comment]
sorry for the delay!  I added this in the last release but will add these enhancements

**Comment by thehesiod** [comment]
bit rot!

**Comment by thehesiod** [comment]
@hugovk it doesn't like something about `ERROR: Failed to resolve requirement from line: -e .[awscli,boto3]` in 3.9 with these changes, not sure what's going on as I don't see how this could have broken the build

**Comment by thehesiod** [comment]
ooo, because this is a development version now

**Pull request merged**
